name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: BC
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Miguel didnt do it we appligize and will find his lazy ass'
        pr-message: 'pull request or rubn tug'
